project:
  type: website

website:
  title: "Grace Cawley"
  navbar:
    left:
      - href: research.qmd
        text: research
      - href: publications.qmd
        text: publications
      - text: blog
        menu:
          - href: sea.qmd
            text: sea
          - href: land.qmd
            text: land

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

editor: visual
