project:
  type: website
  output-dir: docs

website:
  title: "Grace Cawley"
  navbar:
    left:
      - href: research.qmd
        text: research
      - href: publications.qmd
        text: publications
      - text: blog
        menu:
          - href: sea.qmd
            text: sea
          - href: land.qmd
            text: land

