project:
  type: website

website:
  title: "Grace Cawley"
  navbar:
    right: 
      - href: index.qmd
        text: Home
      - research.qmd
      - blog.qmd
      - href: planktonpics.qmd
        text: Plankton Pics
      - icon: twitter
        href: https://twitter.com/planktongrace
      
format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: true

editor: visual

