---
title: ""
---

### CV

### EDUCATION

**Ph.D. Biological Oceanography**, Scripps Institution of Oceanography (UCSD) July 2021 - Present

**M.S. Marine Biology**, Scripps Institution of Oceanography (UCSD) July 2023

**M.S. Environmental and Ocean Sciences**, University of San Diego (USD) August 2020

**B.A. Environmental and Ocean Sciences**, University of San Diego (USD) May 2019 ● Concentration: Marine Ecology ● Minors: Biology and Chemistry

### RESEARCH EXPERIENCE

**PhD Student**, Research Lab of Dr. Moira Décima, SIO July 2021 – Present\
• Led research on pyrosome relevance and environemental drivers in the California Current Ecosystem\
• Lead for zooplankton collection for Decima lab sea-going program\
• Used oceanographic equipment to sample zooplankton communities and water column\
• Mentors high school, undergraduate, and master’s students in completing research projects

**Graduate Researcher**, Research Lab of Dr. Jennifer Prairie, USD June 2019 – August 2020\
• Led research on an experimental project investigating the foraging of copepods on phytoplankton and marine snow at different growth phases and the larger implications for the biological pump\
• Developed methodology and conducted experiments\
• Quantified copepod ingestion rate using both gut fluorescence and stable isotope analysis\
• Grew and maintained phytoplankton cultures, and tracked their growth with microscopy, fluorescence, and a Beckman Coulter counter

**Undergraduate Researcher**, Research Lab of Dr. Jennifer Prairie, USD Spring 2017 - May 2019

### RESEARCH CRUISE EXPERIENCE

(204 Days)

R/V Sally Ride, Santa Lucia Part 2, UCSD (11 Days)

R/V Tangaroa, Great Migration, NIWA (35 Days) October 2024 – November 2024\
R/V Sikuliaq, Seamounts Cruise, University of Alaska: Fairbanks (9 Days) May 2024\
R/V Robert Gordon Sproul, EAT-SLE, UCSD (8 Days) May 2024\
R/V Roger Revelle, CCE-LTER, UCSD (31 Days) February – March 2024\
R/V Sally Ride, CCE IV Test Cruise, UCSD (3 days) October 2023\
R/V Sally Ride, ETNP-OMZ, UCSD (12 Days) March 2023\
R/V Bob and Betty Beyster, Wildfire Cruise, UCSD (1 Day) September 2022\
R/V Roger Revelle, BLOOFINZ, UCSD (56 Days) January – March 2022\
R/V Roger Revelle, CCE-LTER, UCSD (32 Days) July - August 2021\
R/V Sally Ride, CCE-LTER, CalCOFI, UCSD (16 Days) July 2020\
R/V Robert Gordon Sproul, Geopaths, USD (1 Day) Sept 2018, 2019, 2021

### PUBLICATIONS

Cawley, G. F., Décima, M., Mast, A., & Prairie, J. C. (2021). The effect of phytoplankton properties on the ingestion of marine snow by Calanus pacificus. Journal of Plankton Research, 43(6), 957-973. David A. Cushing Award for Best Paper by an Early Career Scientist

Cawley, GF, Mattews, SA, Llopis N, Décima, MR (in prep) From the coast to the western edge of the California current: Pyrosome Atlanticum grazing effects on the ecosystem. In preparation for submission to Limnology and Oceanography.

### CONFERENCE PRESENTATIONS

Cawley GF and Thukral M. Oceanic Plankton as Bioindicators of Climate Change, Oral Presentation, COP28, Dubai, UAE, December 2023

Cael BB, Talley L, Busseler, K, Pötter HO, and Cawley, GF. Plankton and Climate Change: Indicators, Stressors, and Carbon Storage, Panel, COP28, Dubai, UAE, December 2023

Cawley, GF, Mattews, SA, Llopis N, Décima, MR. From the coast to the western edge of the California current: Pyrosome Atlanticum grazing effects on the ecosystem, Oral Presentation, Scripps Student Symposium, San Diego, CA, August 2023

Cawley, GF, Mattews, SA, Llopis N, Décima, MR. From the coast to the western edge of the California current: Pyrosome Atlanticum grazing effects on the ecosystem, Oral Presentation, Ocean Sciences Meeting, Virtual, February 2022

Cawley, GF, Prairie, JC, Decima, MR. Effects of phytoplankton properties on the ingestion by Calanus pacificus, Oral Presentation, Ocean Sciences Meeting, San Diego, CA, February 2020

Cawley, GF, Prairie, JC, Mast, A. Copepod Ingestion of Aggregates formed from Phytoplankton at Different Growth Phase, Poster Presentation, Department Seminar, University of San Diego, May 2019

Cawley, GF, Prairie, JC, Mast, A. Copepod Ingestion of Aggregates formed from Phytoplankton at Different Growth Phase, Poster Presentation, Ocean Sciences Meeting, Portland, OR, February 2018

Cawley, GF, Prairie, JC, Mast, A. Copepod Ingestion of Aggregates formed from Phytoplankton at Different Growth Phase, Poster Presentation, Creative Collaborations, University of San Diego, April 2018 & 2019

### MENTORSHIP

Nilusha Wanniappa, University of California: San Diego, SIO 190 Student September 2021 – June 2022\
Sophia Wu, University of California: San Diego, Peddie School Student July 2023 – August 2023\
Anna McSorely, University of California: San Diego, Undergraduate Student September 2023 – June 2024\
Adrian Chang, University of California: San Diego, Westminster School Student July 2024 – July 2024\
Ethan Jin, University of California: San Diego, Peddie School Student July 2024 – August 2024

### TEACHING

Teaching Assistant, SIO190, Scripps Institution of Oceanography Winter Term 2022

### WORK EXPERIENCE

Lab Technician I, Department of Environmental and Ocean Sciences, USD. August 2020 – June 2021\
• Supported general laboratory and departmental missions\
• Assisted with field equipment and in field sampling\
• Laboratory and Field Equipment operation, training and maintenance\
• Supervised five graduate assistants and five work study students\
• Maintained a reef and native San Diego aquarium tank

Graduate Assistant, Department of Environmental and Ocean Sciences, USD May 2019 – July 2020\
● Provide lab, field, and administrative support to 14 faculty and 3 staff\
● Prepared and set up geological and oceanography labs for undergraduate students\
● Managed maintenance of research aquaria including plumbing, maintaining pH, ammonium, nitrate levels, and fixing equipment (pump, UV, refugium)\
● Trained in Laser Particle Sorter, XRF, Nutrient Analyzer, CTD, YSI, GPS\
● Supported social media and website updates

### OUTREACH

Stay Cool 4 Grandkids, Teacher - September 2022 – Present\
• Present topics of ocean acidification and ocean warming to elementary and middle school students\
• Lead in classroom lab experiments on ocean acidification

SCOPE, Meet a Scientist - September 2022 - Present\
• Introduce a variety of audiences to zooplankton ecology and my path to graduate school

Elementary Institute of Science, Underwater Adventurers Guest Speaker - July 2022\
• Introduce zooplankton to elementary students participating in a ocean themed science camp

Ocean Discovery Institute - Meet a Scientist June 2022

Skype a Scientist - February 2024

National Ocean Science Bowl Spring - 2016 – Present

### SKILLS

• Data Analysis (R, MATLAB, Excel) • Culturing and maintenance of both phytoplankton and zooplankton • Experience writing and coordinating scientific reports and proposals • Background communicating and presenting research to technical and non-technical audiences

### AWARDS

David A. Cushing Award (Journal of Plankton Research) 2021\
EOSC Graduate Travel Funding (Environmental and Ocean Sciences Department, USD) 2020\
Excellence in Research (Environmental and Ocean Science Department, USD) 2019\
Dean Merit Graduate Scholarship (Environmental and Ocean Sciences Department, USD) 2019\
OUR Travel Grant (Office of Undergraduate Research, USD) 2018\
SURE Scholar (Office of Undergraduate Research, USD) 2017

### COMMITTEES

Graduate Student Representative, CCE LTER April 2023 – Present Graduate Student Representative,\
LTER Executive Board July 2023 – December 2023\
Graduate Student Representative, Marine Operations Committee, UCSD November 2023 - Present
