---
title: ""
about:
  id: hero-heading
  template: trestles
  image: grace_in_ctd.HEIC
  links:
    - icon: twitter
      text: twitter
      href: https://x.com/planktongrace
    - icon: github
      text: GitHub
      href: https://github.com
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/planktongrace/
---

### Welcome to my website, I'm Grace!

**Zooplankton Ecologist \| Biogeochemist**

**PhD Candidate** \| Décima Lab \| Scripps Institution of Oceanography

Hey there! I’m a zooplankton ecologist who uses, shipboard measurements, isotopic tracers and machine-learning tools to understand how changing ocean conditions reshape pelagic food webs and biogeochemical cycling. I'm currently exploring the ecological significance and environmental drivers of pyrosomes in the Southern California Bight. Another key aim of my work is to understand how the presence of pyrosomes, along with shifting ecosystem dynamics in the California Current Ecosystem (CCE), is influencing zooplankton communities, with an emphasis on trait-based group shifts.

Additionally, I am working on a project investigating how mixotrophy influences energy transfer through the food web, and the zooplankton dynamics of the the Bluefin Tuna Spawning region in the Indian Ocean. I have also contributed to research on the biogeochemistry of eel breeding zones, including the isotope structure of the zooplankton communities and their abundances.

For my master’s degree at the University of San Diego, I focused on using isotope measurements and gut pigment analysis to determine copepod grazing on marine snow.
